### ISSUE TITLE
Roadmap v1.0

### ISSUE THREAD

**Issue by JakubMrozek** [JakubMrozek/eet#9]
- [ ] dokumentace (README)
- [ ] dokumentace kódu
- [ ] další testy
- [ ] drobný refactoring (některé funkce se zbytečně volají dvakrát atd.)
- [ ] drobnosti (CI, .editorconfig, code coverage atd.)
- [x] lepší chybové hlášky, vracet čísla errorů
- [x] vracet BKP a PKP u chyb #8
- [ ] zadání data tržby nepovinné (vezme se jinak aktuální datum)
- [x] možnost nastavit timeout

**Comment by mfeuermann** [comment]
pekny, mam ted hromadu prace ale zkusim ti casem s necim pomoci...
